In [2]:
#!pip install dash
from dash import Dash, dcc, html, Input, Output
import plotly.graph_objects as go
import numpy as np
import pandas as pd
from plotly.subplots import make_subplots

In [3]:
#df = pd.read_csv(r"C:\Users\ollya\OneDrive\Dashboard Project\archive\races.csv")
df = pd.read_csv(r"C:\Users\PC\OneDrive\Dashboard Project\archive\races.csv")


df = df[df['year'] == 2024]
df = df[['raceId', 'year', 'name', 'date', 'circuitId']]
df['name'] = df['name'].str.replace('Grand Prix', '').str.strip()
df

      raceId  year            name        date  circuitId
1101    1121  2024         Bahrain  2024-03-02          3
1102    1122  2024   Saudi Arabian  2024-03-09         77
1103    1123  2024      Australian  2024-03-24          1
1104    1124  2024        Japanese  2024-04-07         22
1105    1125  2024         Chinese  2024-04-21         17
1106    1126  2024           Miami  2024-05-05         79
1107    1127  2024  Emilia Romagna  2024-05-19         21
1108    1128  2024          Monaco  2024-05-26          6
1109    1129  2024        Canadian  2024-06-09          7
1110    1130  2024         Spanish  2024-06-23          4
1111    1131  2024        Austrian  2024-06-30         70
1112    1132  2024         British  2024-07-07          9
1113    1133  2024       Hungarian  2024-07-21         11
1114    1134  2024         Belgian  2024-07-28         13
1115    1135  2024           Dutch  2024-08-25         39
1116    1136  2024         Italian  2024-09-01         14
1117    1137  2024      Azerbaijan  2024-09-15         73
1118    1138  2024       Singapore  2024-09-22         15
1119    1139  2024   United States  2024-10-20         69
1120    1140  2024     Mexico City  2024-10-27         32
1121    1141  2024       São Paulo  2024-11-03         18
1122    1142  2024       Las Vegas  2024-11-23         80
1123    1143  2024           Qatar  2024-12-01         78
1124    1144  2024       Abu Dhabi  2024-12-08         24

In [4]:
#df2 = pd.read_csv(r"C:\Users\ollya\OneDrive\Dashboard Project\archive\results.csv")
df2 = pd.read_csv(r"C:\Users\PC\OneDrive\Dashboard Project\archive\results.csv")

#df2 = df2[df2['raceId'] == 1132]
x = df2['driverId']
x

0          1
1          2
2          3
3          4
4          5
        ...
26754    825
26755    859
26756    822
26757    861
26758    815
Name: driverId, Length: 26759, dtype: int64

In [5]:
#df3 = pd.read_csv(r"C:\Users\ollya\OneDrive\Dashboard Project\archive\drivers.csv")
df3 = pd.read_csv(r"C:\Users\PC\OneDrive\Dashboard Project\archive\drivers.csv")

df3 = df3.drop(columns=['number'])
df3 = df3[(df3.driverId.isin(x))]
df3

,driverId,driverRef,code,forename,surname,dob,nationality,url
0,1,hamilton,HAM,Lewis,Hamilton,1985-01-07,British,http://en.wikipedia.org/wiki/Lewis_Hamilton
1,2,heidfeld,HEI,Nick,Heidfeld,1977-05-10,German,http://en.wikipedia.org/wiki/Nick_Heidfeld
2,3,rosberg,ROS,Nico,Rosberg,1985-06-27,German,http://en.wikipedia.org/wiki/Nico_Rosberg
3,4,alonso,ALO,Fernando,Alonso,1981-07-29,Spanish,http://en.wikipedia.org/wiki/Fernando_Alonso
4,5,kovalainen,KOV,Heikki,Kovalainen,1981-10-19,Finnish,http://en.wikipedia.org/wiki/Heikki_Kovalainen
...,...,...,...,...,...,...,...,...
856,858,sargeant,SAR,Logan,Sargeant,2000-12-31,American,http://en.wikipedia.org/wiki/Logan_Sargeant
857,859,lawson,LAW,Liam,Lawson,2002-02-11,New Zealander,http://en.wikipedia.org/wiki/Liam_Lawson
858,860,bearman,BEA,Oliver,Bearman,2005-05-08,British,http://en.wikipedia.org/wiki/Oliver_Bearman
859,861,colapinto,COL,Franco,Colapinto,2003-05-27,Argentinian,http://en.wikipedia.org/wiki/Franco_Colapinto
860,862,doohan,DOO,Jack,Doohan,2003-01-20,Australian,http://en.wikipedia.org/wiki/Jack_Doohan

In [6]:
df4 = df2.merge(df3, on='driverId', how='left')
df4['fullname'] = df4['forename'] + ' ' + df4['surname']
df4

,resultId,raceId,driverId,constructorId,number,grid,position,positionText,positionOrder,points,...,fastestLapSpeed,statusId,driverRef,code,forename,surname,dob,nationality,url,fullname
0,1,18,1,1,22,1,1,1,1,10.0,...,218.300,1,hamilton,HAM,Lewis,Hamilton,1985-01-07,British,http://en.wikipedia.org/wiki/Lewis_Hamilton,Lewis Hamilton
1,2,18,2,2,3,5,2,2,2,8.0,...,217.586,1,heidfeld,HEI,Nick,Heidfeld,1977-05-10,German,http://en.wikipedia.org/wiki/Nick_Heidfeld,Nick Heidfeld
2,3,18,3,3,7,7,3,3,3,6.0,...,216.719,1,rosberg,ROS,Nico,Rosberg,1985-06-27,German,http://en.wikipedia.org/wiki/Nico_Rosberg,Nico Rosberg
3,4,18,4,4,5,11,4,4,4,5.0,...,215.464,1,alonso,ALO,Fernando,Alonso,1981-07-29,Spanish,http://en.wikipedia.org/wiki/Fernando_Alonso,Fernando Alonso
4,5,18,5,1,23,3,5,5,5,4.0,...,218.385,1,kovalainen,KOV,Heikki,Kovalainen,1981-10-19,Finnish,http://en.wikipedia.org/wiki/Heikki_Kovalainen,Heikki Kovalainen
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26754,26760,1144,825,210,20,14,16,16,16,0.0,...,222.002,11,kevin_magnussen,MAG,Kevin,Magnussen,1992-10-05,Danish,http://en.wikipedia.org/wiki/Kevin_Magnussen,Kevin Magnussen
26755,26761,1144,859,215,30,12,17,17,17,0.0,...,214.212,5,lawson,LAW,Liam,Lawson,2002-02-11,New Zealander,http://en.wikipedia.org/wiki/Liam_Lawson,Liam Lawson
26756,26762,1144,822,15,77,9,\N,R,18,0.0,...,212.462,130,bottas,BOT,Valtteri,Bottas,1989-08-28,Finnish,http://en.wikipedia.org/wiki/Valtteri_Bottas,Valtteri Bottas
26757,26763,1144,861,3,43,20,\N,R,19,0.0,...,212.631,5,colapinto,COL,Franco,Colapinto,2003-05-27,Argentinian,http://en.wikipedia.org/wiki/Franco_Colapinto,Franco Colapinto
26758,26764,1144,815,9,11,10,\N,R,20,0.0,...,\N,4,perez,PER,Sergio,Pérez,1990-01-26,Mexican,http://en.wikipedia.org/wiki/Sergio_P%C3%A9rez,Sergio Pérez

In [7]:
df5 = df4.merge(df, on='raceId', how='left')
df5 = df5[df5['year'] == 2024]
df5.columns

Index(['resultId', 'raceId', 'driverId', 'constructorId', 'number', 'grid',
       'position', 'positionText', 'positionOrder', 'points', 'laps', 'time',
       'milliseconds', 'fastestLap', 'rank', 'fastestLapTime',
       'fastestLapSpeed', 'statusId', 'driverRef', 'code', 'forename',
       'surname', 'dob', 'nationality', 'url', 'fullname', 'year', 'name',
       'date', 'circuitId'],
      dtype='object')

In [8]:
df6 = pd.read_csv(r"C:\Users\PC\OneDrive\Dashboard Project\archive\constructors.csv")
df6 = df6[df6['constructorId'].isin(df5['constructorId'])]
df6 =df6.rename(columns={'name' : 'constructor_name'})
df6

,constructorId,constructorRef,constructor_name,nationality,url
0,1,mclaren,McLaren,British,http://en.wikipedia.org/wiki/McLaren
2,3,williams,Williams,British,http://en.wikipedia.org/wiki/Williams_Grand_Pr...
5,6,ferrari,Ferrari,Italian,http://en.wikipedia.org/wiki/Scuderia_Ferrari
8,9,red_bull,Red Bull,Austrian,http://en.wikipedia.org/wiki/Red_Bull_Racing
14,15,sauber,Sauber,Swiss,http://en.wikipedia.org/wiki/Sauber_Motorsport
115,117,aston_martin,Aston Martin,British,http://en.wikipedia.org/wiki/Aston_Martin_in_F...
129,131,mercedes,Mercedes,German,http://en.wikipedia.org/wiki/Mercedes-Benz_in_...
207,210,haas,Haas F1 Team,American,http://en.wikipedia.org/wiki/Haas_F1_Team
210,214,alpine,Alpine F1 Team,French,http://en.wikipedia.org/wiki/Alpine_F1_Team
211,215,rb,RB F1 Team,Italian,http://en.wikipedia.org/wiki/RB_Formula_One_Team

In [9]:
df7 = df5.merge(df6, on='constructorId', how='left')
df7.columns

Index(['resultId', 'raceId', 'driverId', 'constructorId', 'number', 'grid',
       'position', 'positionText', 'positionOrder', 'points', 'laps', 'time',
       'milliseconds', 'fastestLap', 'rank', 'fastestLapTime',
       'fastestLapSpeed', 'statusId', 'driverRef', 'code', 'forename',
       'surname', 'dob', 'nationality_x', 'url_x', 'fullname', 'year', 'name',
       'date', 'circuitId', 'constructorRef', 'constructor_name',
       'nationality_y', 'url_y'],
      dtype='object')

In [10]:
df_longlat = pd.read_csv(r"C:\Users\PC\OneDrive\Dashboard Project\archive\circuits.csv")
df_longlat = df_longlat.rename(columns={'name' : 'circuit_name'})

df7 = df7.merge(df_longlat, on='circuitId', how = 'left' )
df7

,resultId,raceId,driverId,constructorId,number,grid,position,positionText,positionOrder,points,...,nationality_y,url_y,circuitRef,circuit_name,location,country,lat,lng,alt,url
0,26286,1121,830,9,1,1,1,1,1,26.0,...,Austrian,http://en.wikipedia.org/wiki/Red_Bull_Racing,bahrain,Bahrain International Circuit,Sakhir,Bahrain,26.0325,50.5106,7,http://en.wikipedia.org/wiki/Bahrain_Internati...
1,26287,1121,815,9,11,5,2,2,2,18.0,...,Austrian,http://en.wikipedia.org/wiki/Red_Bull_Racing,bahrain,Bahrain International Circuit,Sakhir,Bahrain,26.0325,50.5106,7,http://en.wikipedia.org/wiki/Bahrain_Internati...
2,26288,1121,832,6,55,4,3,3,3,15.0,...,Italian,http://en.wikipedia.org/wiki/Scuderia_Ferrari,bahrain,Bahrain International Circuit,Sakhir,Bahrain,26.0325,50.5106,7,http://en.wikipedia.org/wiki/Bahrain_Internati...
3,26289,1121,844,6,16,2,4,4,4,12.0,...,Italian,http://en.wikipedia.org/wiki/Scuderia_Ferrari,bahrain,Bahrain International Circuit,Sakhir,Bahrain,26.0325,50.5106,7,http://en.wikipedia.org/wiki/Bahrain_Internati...
4,26290,1121,847,131,63,3,5,5,5,10.0,...,German,http://en.wikipedia.org/wiki/Mercedes-Benz_in_...,bahrain,Bahrain International Circuit,Sakhir,Bahrain,26.0325,50.5106,7,http://en.wikipedia.org/wiki/Bahrain_Internati...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
474,26760,1144,825,210,20,14,16,16,16,0.0,...,American,http://en.wikipedia.org/wiki/Haas_F1_Team,yas_marina,Yas Marina Circuit,Abu Dhabi,UAE,24.4672,54.6031,3,http://en.wikipedia.org/wiki/Yas_Marina_Circuit
475,26761,1144,859,215,30,12,17,17,17,0.0,...,Italian,http://en.wikipedia.org/wiki/RB_Formula_One_Team,yas_marina,Yas Marina Circuit,Abu Dhabi,UAE,24.4672,54.6031,3,http://en.wikipedia.org/wiki/Yas_Marina_Circuit
476,26762,1144,822,15,77,9,\N,R,18,0.0,...,Swiss,http://en.wikipedia.org/wiki/Sauber_Motorsport,yas_marina,Yas Marina Circuit,Abu Dhabi,UAE,24.4672,54.6031,3,http://en.wikipedia.org/wiki/Yas_Marina_Circuit
477,26763,1144,861,3,43,20,\N,R,19,0.0,...,British,http://en.wikipedia.org/wiki/Williams_Grand_Pr...,yas_marina,Yas Marina Circuit,Abu Dhabi,UAE,24.4672,54.6031,3,http://en.wikipedia.org/wiki/Yas_Marina_Circuit
478,26764,1144,815,9,11,10,\N,R,20,0.0,...,Austrian,http://en.wikipedia.org/wiki/Red_Bull_Racing,yas_marina,Yas Marina Circuit,Abu Dhabi,UAE,24.4672,54.6031,3,http://en.wikipedia.org/wiki/Yas_Marina_Circuit

In [11]:
print(df7.position.unique())
df7.position = df7['position'].replace(['\\N', ''])
df7.position = df7['position'].astype(int)

['1' '2' '3' '4' '5' '6' '7' '8' '9' '10' '11' '12' '13' '14' '15' '16'
 '17' '18' '19' '20' '\\N']

In [12]:
df7['constructorRef'] = df7['constructorRef'].str.replace("_", " ")
df7.constructorRef = df7.constructorRef.str.title()

In [32]:

df7['milliseconds'] = df7['milliseconds'].replace(r'\N', '')
print(df7['milliseconds'])
df7['laptime'] = pd.to_datetime(df7['milliseconds'], unit='ms').dt.time
df7['laptime']

0      5504742
1      5527199
2      5529852
3      5544411
4      5551530
        ...
474
475
476
477
478
Name: milliseconds, Length: 479, dtype: object

0      01:31:44.742000
1      01:32:07.199000
2      01:32:09.852000
3      01:32:24.411000
4      01:32:31.530000
            ...
474                NaT
475                NaT
476                NaT
477                NaT
478                NaT
Name: laptime, Length: 479, dtype: object

In [13]:
#df7.to_csv(r'C:\Users\PC\OneDrive\Dashboard Project\Code\cleaned_data.csv')

In [14]:
"""from dash import Dash, dcc, html, Input, Output
import plotly.express as px
import dash_bootstrap_components as dbc
import plotly.io as pio 

pio.templates.default = "ggplot2"


app = Dash(__name__, external_stylesheets=[dbc.themes.LUX])

app.layout = dbc.Container(

##Title Row
    [
        dbc.Row([
            dbc.Col(
                html.H1(
                    children = "F1 Dashboard",
                    style = {
                        'textAlign': 'center',
                        'color': 'black',
                    }),
                width={"size" : 15},
            )
        ]),

##Dropdown Row
        dbc.Row([
            dbc.Col(
                dcc.Dropdown(
                    id = "dropdown",
                    options = [{'label': i, 'value': i} for i in df5['fullname'].unique()],
                    value = df7['fullname'].unique()[0],
                    clearable = False,
                    className = "mb-3"
                )
            )
        ], class_name="mb-3"),

#First Graph Row
        dbc.Row([
            dbc.Col(dcc.Graph(id='graph-position'), width=5),
            dbc.Col(dcc.Graph(id='graph-points'), width=5),
            dbc.Col(
                dbc.Card(id='info-card',
                    style = {'height': '100%',
                        'textAlign': 'center'}
                    ), width = 2,
                    style = {'minHeight': '500px'}
                ) 
                ], class_name="mb-3"
        ),

        dbc.Row([
            dbc.Col(
                dcc.Dropdown(
                    id = "dropdown_constructors",
                    options = [{'label' : i, 'value' : i} for i in df7['constructorRef'].unique()],
                    value = df7['constructorRef'].unique()[0],
                    style = {'width' : '3'},
                )   
            )
        ], className = "mb-3"),

        dbc.Row([
            dbc.Col(dcc.Graph(id='constructor_performance'), width=6),
            dbc.Col([dcc.Store(id='dummy', data='load'),
                    dcc.Graph(id='race_map_graph')], width = 6)
        ], className = "mb-3")      
    ], fluid=True
)


    

@app.callback(
    Output('graph-position', 'figure'),
    Output('graph-points', 'figure'),
    Output('info-card', 'children'),
    Input('dropdown', 'value'),
)


def generate_graphs(driver):

    df = df7[df7['fullname'] == driver]
    df['moving_avg'] = df['position'].rolling(window=3, min_periods=1).mean()
    df['cumulative_points'] = df['points'].cumsum()
    x = df['points'].cumsum()
    df['date'] = pd.to_datetime(df['date'])
    df = df.sort_values(by='date')


##################### First Row
    fig_position = go.Figure()
    
    fig_position.add_trace(go.Bar(
        x = df['name'],
        y = df['position'],
        name = 'Race Position',
        marker_color = 'blue',
    ))

    fig_position.add_trace(go.Scatter(
        x = df['name'],
        y = df['moving_avg'],
        mode = 'lines+markers',
        name = 'Moving Average',
        line = dict(color='red', width=2),
    ))

    fig_position.update_layout(
        title=f'Position of {driver} in 2024 Season',
        xaxis_title = 'Grand Prix',
        barmode = 'overlay'
    )

#####################

    fig_points = make_subplots(rows=1, cols=1, specs=[[{"secondary_y": True}]])

    fig_points.add_trace(go.Bar(
        x = df['name'],
        y = df['points'],
        name = 'Points',
        marker_color = 'green',
    ))

    fig_points.add_trace(go.Scatter(
        x = df['name'],
        y = df['cumulative_points'],
        mode = 'lines+markers',
        name = 'Cumulative Points',
        line = dict(color='orange', width=2),
    ), secondary_y=True)

    fig_points.update_layout(
        title=f'Points of {driver} in 2024 Season',
        xaxis_title = 'Grand Prix',
        barmode = 'overlay'
    )
#####################

    card = [
    dbc.CardHeader(html.H2(f"{driver}")),
    dbc.CardBody([
        html.H4(f"{driver} has scored {x.iloc[-1]} points this season."),
        html.H4(f"This is equal to {df['points'].mean().round()} points a race."),
        html.H4(f"They finished on average in {df['position'].mean().round()} place each race")
        
        ])
    ]

    return fig_position, fig_points, card


@app.callback(
    Output('constructor_performance', 'figure'),
    Input('dropdown_constructors', 'value'),
)

def update_constructors(selected_constructor):
    df_constructor = df7[df7['constructorRef'] == selected_constructor]
    df_constructor['date'] = pd.to_datetime(df['date'])
    df_constructor = df_constructor.sort_values(by='date')
    df_constructor['constructor_points'] = df_constructor['points']
    df_constructor['constructor_points_cumulative'] = df_constructor['constructor_points'].groupby(df_constructor['constructorRef']).cumsum()
    df_constructor['cum_points'] = df_constructor.groupby('raceId')['constructor_points_cumulative'].transform('max')

    fig_constructor_points = make_subplots(rows=1, cols=1, specs=[[{"secondary_y": True}]])

    fig_constructor_points.add_trace(go.Bar(
        x = df_constructor['name'],
        y = df_constructor['constructor_points'],
        name = 'Points',
        marker_color = 'green',
    ))

    fig_constructor_points.add_trace(go.Scatter(
        x = df_constructor['name'],
        y = df_constructor['cum_points'],
        mode = 'lines+markers',
        name = 'Cumulative Points',
        line = dict(color='orange', width=2),
    ), secondary_y=True)

    return fig_constructor_points

@app.callback(
    Output('race_map_graph', 'figure'),
    Input('dummy', 'data')
)

def race_map(_):
    df = df7
    race_map = go.Figure()

    race_map.add_trace(go.Scattergeo(
        lat = df['lat'],
        lon = df['lng'],
        text = df['circuit_name'] + ' Grand Prix',
        mode = 'markers',
        marker = dict(size=8, color='red'),
    ))

    return race_map




if __name__ == '__main__':
    app.run(debug=True)"""

'from dash import Dash, dcc, html, Input, Output\nimport plotly.express as px\nimport dash_bootstrap_components as dbc\nimport plotly.io as pio \n\npio.templates.default = "ggplot2"\n\n\napp = Dash(__name__, external_stylesheets=[dbc.themes.LUX])\n\napp.layout = dbc.Container(\n\n##Title Row\n    [\n        dbc.Row([\n            dbc.Col(\n                html.H1(\n                    children = "F1 Dashboard",\n                    style = {\n                        \'textAlign\': \'center\',\n                        \'color\': \'black\',\n                    }),\n                width={"size" : 15},\n            )\n        ]),\n\n##Dropdown Row\n        dbc.Row([\n            dbc.Col(\n                dcc.Dropdown(\n                    id = "dropdown",\n                    options = [{\'label\': i, \'value\': i} for i in df5[\'fullname\'].unique()],\n                    value = df7[\'fullname\'].unique()[0],\n                    clearable = False,\n                    className = "mb-3"\n                )\n            )\n        ], class_name="mb-3"),\n\n#First Graph Row\n        dbc.Row([\n            dbc.Col(dcc.Graph(id=\'graph-position\'), width=5),\n            dbc.Col(dcc.Graph(id=\'graph-points\'), width=5),\n            dbc.Col(\n                dbc.Card(id=\'info-card\',\n                    style = {\'height\': \'100%\',\n                        \'textAlign\': \'center\'}\n                    ), width = 2,\n                    style = {\'minHeight\': \'500px\'}\n                ) \n                ], class_name="mb-3"\n        ),\n\n        dbc.Row([\n            dbc.Col(\n                dcc.Dropdown(\n                    id = "dropdown_constructors",\n                    options = [{\'label\' : i, \'value\' : i} for i in df7[\'constructorRef\'].unique()],\n                    value = df7[\'constructorRef\'].unique()[0],\n                    style = {\'width\' : \'3\'},\n                )   \n            )\n        ], className = "mb-3"),\n\n        dbc.Row([\n            dbc.Col(dcc.Graph(id=\'constructor_performance\'), width=6),\n            dbc.Col([dcc.Store(id=\'dummy\', data=\'load\'),\n                    dcc.Graph(id=\'race_map_graph\')], width = 6)\n        ], className = "mb-3")      \n    ], fluid=True\n)\n\n\n    \n\n@app.callback(\n    Output(\'graph-position\', \'figure\'),\n    Output(\'graph-points\', \'figure\'),\n    Output(\'info-card\', \'children\'),\n    Input(\'dropdown\', \'value\'),\n)\n\n\ndef generate_graphs(driver):\n\n    df = df7[df7[\'fullname\'] == driver]\n    df[\'moving_avg\'] = df[\'position\'].rolling(window=3, min_periods=1).mean()\n    df[\'cumulative_points\'] = df[\'points\'].cumsum()\n    x = df[\'points\'].cumsum()\n    df[\'date\'] = pd.to_datetime(df[\'date\'])\n    df = df.sort_values(by=\'date\')\n\n\n##################### First Row\n    fig_position = go.Figure()\n    \n    fig_position.add_trace(go.Bar(\n        x = df[\'name\'],\n        y = df[\'position\'],\n        name = \'Race Position\',\n        marker_color = \'blue\',\n    ))\n\n    fig_position.add_trace(go.Scatter(\n        x = df[\'name\'],\n        y = df[\'moving_avg\'],\n        mode = \'lines+markers\',\n        name = \'Moving Average\',\n        line = dict(color=\'red\', width=2),\n    ))\n\n    fig_position.update_layout(\n        title=f\'Position of {driver} in 2024 Season\',\n        xaxis_title = \'Grand Prix\',\n        barmode = \'overlay\'\n    )\n\n#####################\n\n    fig_points = make_subplots(rows=1, cols=1, specs=[[{"secondary_y": True}]])\n\n    fig_points.add_trace(go.Bar(\n        x = df[\'name\'],\n        y = df[\'points\'],\n        name = \'Points\',\n        marker_color = \'green\',\n    ))\n\n    fig_points.add_trace(go.Scatter(\n        x = df[\'name\'],\n        y = df[\'cumulative_points\'],\n        mode = \'lines+markers\',\n        name = \'Cumulative Points\',\n        line = dict(color=\'orange\', width=2),\n    ), secondary_y=True)\n\n    fig_points.update_layout(\n        title=f\'Points of {driver} in 2024 Season\',\n        xaxis_title = \'Grand Prix\',\n        barmode = \'overlay\'\n    )\n#####################\n\n    card = [\n    dbc.CardHeader(html.H2(f"{driver}")),\n    dbc.CardBody([\n        html.H4(f"{driver} has scored {x.iloc[-1]} points this season."),\n        html.H4(f"This is equal to {df[\'points\'].mean().round()} points a race."),\n        html.H4(f"They finished on average in {df[\'position\'].mean().round()} place each race")\n        \n        ])\n    ]\n\n    return fig_position, fig_points, card\n\n\n@app.callback(\n    Output(\'constructor_performance\', \'figure\'),\n    Input(\'dropdown_constructors\', \'value\'),\n)\n\ndef update_constructors(selected_constructor):\n    df_constructor = df7[df7[\'constructorRef\'] == selected_constructor]\n    df_constructor[\'date\'] = pd.to_datetime(df[\'date\'])\n    df_constructor = df_constructor.sort_values(by=\'date\')\n    df_constructor[\'constructor_points\'] = df_constructor[\'points\']\n    df_constructor[\'constructor_points_cumulative\'] = df_constructor[\'constructor_points\'].groupby(df_constructor[\'constructorRef\']).cumsum()\n    df_constructor[\'cum_points\'] = df_constructor.groupby(\'raceId\')[\'constructor_points_cumulative\'].transform(\'max\')\n\n    fig_constructor_points = make_subplots(rows=1, cols=1, specs=[[{"secondary_y": True}]])\n\n    fig_constructor_points.add_trace(go.Bar(\n        x = df_constructor[\'name\'],\n        y = df_constructor[\'constructor_points\'],\n        name = \'Points\',\n        marker_color = \'green\',\n    ))\n\n    fig_constructor_points.add_trace(go.Scatter(\n        x = df_constructor[\'name\'],\n        y = df_constructor[\'cum_points\'],\n        mode = \'lines+markers\',\n        name = \'Cumulative Points\',\n        line = dict(color=\'orange\', width=2),\n    ), secondary_y=True)\n\n    return fig_constructor_points\n\n@app.callback(\n    Output(\'race_map_graph\', \'figure\'),\n    Input(\'dummy\', \'data\')\n)\n\ndef race_map(_):\n    df = df7\n    race_map = go.Figure()\n\n    race_map.add_trace(go.Scattergeo(\n        lat = df[\'lat\'],\n        lon = df[\'lng\'],\n        text = df[\'circuit_name\'] + \' Grand Prix\',\n        mode = \'markers\',\n        marker = dict(size=8, color=\'red\'),\n    ))\n\n    return race_map\n\n\n\n\nif __name__ == \'__main__\':\n    app.run(debug=True)'